use rustpython_vm::{
    builtins::{PyModule as RpModule, PyStrRef},
    convert::ToPyObject,
    PyObjectRef, Py,
};

use crate::{
    err::{from_vm_result, PyResult},
    instance::Bound,
    python::Python,
    types::PyAny,
};

/// Marker type for a Python module object. Analogous to PyO3's `PyModule`.
pub struct PyModule;

impl PyModule {
    /// Import a Python module by name. Equivalent to `import name`.
    pub fn import<'py>(py: Python<'py>, name: &str) -> PyResult<Bound<'py, PyModule>> {
        let vm = py.vm;
        let interned = vm.ctx.intern_str(name);
        let module = from_vm_result(vm.import(interned, 0))?;
        Ok(Bound::from_object(py, module))
    }
}

impl<'py> Bound<'py, PyModule> {
    /// Construct from a raw `PyObjectRef` known to be a module.
    #[doc(hidden)]
    pub fn from_module_obj(py: Python<'py>, obj: PyObjectRef) -> Self {
        Bound::from_object(py, obj)
    }

    /// Construct from a `&Py<RpModule>` as received by a `ModuleExec` slot.
    #[doc(hidden)]
    pub fn from_exec_ref(py: Python<'py>, module: &Py<RpModule>) -> Self {
        // to_owned increments the refcount giving an owned PyRef<RpModule>,
        // then into() erases the type tag to PyObjectRef.
        let obj: PyObjectRef = module.to_owned().into();
        Bound::from_object(py, obj)
    }

    /// Add a Python callable (from `wrap_pyfunction!`) to this module.
    ///
    /// Uses the function's `__name__` attribute as the attribute name.
    pub fn add_function(&self, func: Bound<'py, PyAny>) -> PyResult<()> {
        let vm = self.py.vm;
        let name_obj = from_vm_result(func.obj.get_attr("__name__", vm))?;
        // Extract as PyStrRef so we have an AsPyStr-compatible value.
        let name_ref: PyStrRef = from_vm_result(name_obj.try_into_value(vm))?;
        from_vm_result(self.obj.set_attr(&name_ref, func.obj, vm))
    }

    /// Add an arbitrary named attribute to this module.
    ///
    /// The name is interned so it satisfies RustPython's `AsPyStr` bound.
    pub fn add(&self, name: &str, value: impl ToPyObject) -> PyResult<()> {
        let vm = self.py.vm;
        let py_val = value.to_pyobject(vm);
        let interned = vm.ctx.intern_str(name);
        from_vm_result(self.obj.set_attr(interned, py_val, vm))
    }

    /// Register a `#[pyclass]` type with this module.
    ///
    /// The class is created via `T::make_class` and attached as an attribute
    /// using its Python-side name. Property accessors generated by
    /// `#[pyo3(get)]` / `#[pyo3(set)]` are registered separately.
    pub fn add_class<T>(&self) -> crate::err::PyResult<()>
    where
        T: ::rustpython_vm::PyPayload
            + ::rustpython_vm::class::PyClassImpl
            + ::rustpython_vm::class::StaticType
            + crate::Pyo3Accessors,
    {
        let vm = self.py.vm;
        let class = T::make_class(&vm.ctx);

        // Register property accessors for #[pyo3(get)] / #[pyo3(set)] fields.
        // Safety: StaticType guarantees a stable static reference.
        let class_static = T::static_type();
        T::__pyo3_register_accessors(&vm.ctx, class_static);

        // Wire dunder methods (__repr__, __str__, etc.) to their corresponding
        // type slots. Static types created via `new_static` don't call
        // `init_slots` automatically, so we set the slots directly.
        crate::slots::fixup_dunder_slots(class_static, &vm.ctx);

        let name = <T as ::rustpython_vm::class::PyClassDef>::NAME;
        let interned = vm.ctx.intern_str(name);
        let class_obj: PyObjectRef = class.into();
        from_vm_result(self.obj.set_attr(interned, class_obj, vm))
    }
}
