use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{FnArg, ItemFn, Pat, Result, ReturnType};

pub fn expand(_attr: TokenStream, input: ItemFn) -> Result<TokenStream> {
    let fn_name = &input.sig.ident;
    let fn_name_str = fn_name.to_string();
    let wrapper_name = format_ident!("__pyo3_fn_{}", fn_name);

    // Analyse arguments, collecting:
    //   rp_params  – RustPython closure parameter declarations
    //   call_exprs – expressions to pass to the original function
    let mut rp_params: Vec<TokenStream> = vec![];
    let mut call_exprs: Vec<TokenStream> = vec![];

    for arg in &input.sig.inputs {
        let FnArg::Typed(pat_type) = arg else {
            return Err(syn::Error::new_spanned(arg, "self arguments not yet supported"));
        };

        let pat_name = match pat_type.pat.as_ref() {
            Pat::Ident(pi) => pi.ident.clone(),
            other => return Err(syn::Error::new_spanned(other, "unsupported argument pattern")),
        };

        let ty = &pat_type.ty;
        let ty_str = quote!(#ty).to_string().replace(' ', "");

        // Python<'_> → inject VM token; no rp_param for it.
        if ty_str.contains("Python") {
            call_exprs.push(quote! { ::pyo3::Python::from_vm(__vm) });
            continue;
        }

        let (rp_ty, call_expr) = map_type(&ty_str, &pat_name)?;
        rp_params.push(quote! { #pat_name: #rp_ty });
        call_exprs.push(call_expr);
    }

    // Determine how to handle the return type.
    let (ret_annotation, ret_transform) = return_handling(&input.sig.output);

    // Build closure params: rp_params first, then the VM at the end.
    // Using a single vec avoids the double-comma from #(#rp_params,)* + leading comma.
    let mut all_params = rp_params.clone();
    all_params.push(quote! { __vm: &::rustpython_vm::VirtualMachine });

    Ok(quote! {
        // Original function is kept exactly as written.
        #input

        /// Generated by `#[pyo3::pyfunction]`. Creates a Python callable.
        #[doc(hidden)]
        #[allow(non_snake_case, dead_code)]
        pub fn #wrapper_name<'__py>(
            __py: ::pyo3::Python<'__py>,
        ) -> ::pyo3::Bound<'__py, ::pyo3::types::PyAny> {
            let __vm = __py.vm();
            let __heap_def = __vm.ctx.new_method_def(
                #fn_name_str,
                |#(#all_params),*| #ret_annotation {
                    let __result = #fn_name(#(#call_exprs),*);
                    #ret_transform
                },
                ::rustpython_vm::function::PyMethodFlags::empty(),
                None,
            );
            // build_function wraps HeapMethodDef into a PyNativeFunction,
            // which is a real Python callable with __name__, __doc__, etc.
            let __callable = __heap_def.build_function(__vm);
            ::pyo3::Bound::from_object(__py, __callable.into())
        }
    })
}

fn map_type(ty_str: &str, name: &syn::Ident) -> Result<(TokenStream, TokenStream)> {
    match ty_str {
        "&str" => Ok((
            quote! { ::rustpython_vm::builtins::PyStrRef },
            quote! { #name.as_str() },
        )),
        "String" => Ok((
            quote! { ::rustpython_vm::builtins::PyStrRef },
            quote! { #name.to_string() },
        )),
        "i8" | "i16" | "i32" | "i64" => {
            let t: TokenStream = ty_str.parse().unwrap();
            Ok((quote! { i64 }, quote! { #name as #t }))
        }
        "u8" | "u16" | "u32" | "u64" | "usize" => {
            let t: TokenStream = ty_str.parse().unwrap();
            Ok((quote! { u64 }, quote! { #name as #t }))
        }
        "f32" | "f64" => {
            let t: TokenStream = ty_str.parse().unwrap();
            Ok((quote! { f64 }, quote! { #name as #t }))
        }
        "bool" => Ok((
            quote! { ::rustpython_vm::function::ArgIntoBool },
            quote! { #name.into() },
        )),
        "Vec<u8>" => Ok((
            quote! { ::rustpython_vm::builtins::PyBytesRef },
            quote! { #name.as_bytes().to_vec() },
        )),
        other if other.contains("Bound") => Ok((
            quote! { ::rustpython_vm::PyObjectRef },
            quote! {
                &::pyo3::Bound::from_object(::pyo3::Python::from_vm(__vm), #name)
            },
        )),
        _ => Err(syn::Error::new(
            proc_macro2::Span::call_site(),
            format!("unsupported argument type: `{}`", ty_str),
        )),
    }
}

fn return_handling(ret: &ReturnType) -> (TokenStream, TokenStream) {
    match ret {
        ReturnType::Default => (quote! {}, quote! { __result }),
        ReturnType::Type(_, ty) => {
            let ty_str = quote!(#ty).to_string().replace(' ', "");
            if ty_str.contains("PyResult") {
                (
                    quote! { -> ::rustpython_vm::PyResult<_> },
                    quote! { __result.map_err(::pyo3::err::into_vm_err) },
                )
            } else {
                (quote! {}, quote! { __result })
            }
        }
    }
}
