use proc_macro2::TokenStream;
use quote::quote;
use syn::{FnArg, ImplItem, ImplItemFn, ItemImpl, Pat, Result};

/// Expand `#[pymethods]` on an impl block.
///
/// Transforms a pyo3-style impl block into a rustpython-vm-style impl block:
/// - `#[new]` -> Constructor trait impl
/// - `__repr__`, `__str__`, etc. -> `#[pymethod]` (rustpython handles dunders)
/// - Regular methods -> `#[pymethod]`
/// - `#[getter]` / `#[setter]` -> `#[pygetset]` / `#[pygetset(setter)]`
/// - `#[staticmethod]` -> `#[pystaticmethod]`
/// - `#[classmethod]` -> `#[pyclassmethod]`
///
/// Also invokes the `__pyo3_accessors_StructName!()` macro (generated by
/// `#[pyclass]`) to include getter/setter methods for `#[pyo3(get, set)]` fields.
pub fn expand(_attr: TokenStream, input: ItemImpl) -> Result<TokenStream> {
    let self_ty = &input.self_ty;

    let mut has_new = false;
    let mut new_method: Option<ImplItemFn> = None;
    let mut transformed_items: Vec<TokenStream> = Vec::new();

    for item in &input.items {
        let ImplItem::Fn(method) = item else {
            // Pass through non-function items (type aliases, consts, etc.)
            transformed_items.push(quote! { #item });
            continue;
        };

        if has_attr(&method.attrs, "new") {
            has_new = true;
            new_method = Some(method.clone());
            // Keep the original method (without the #[new] attr) as a helper.
            let cleaned = strip_pyo3_method_attrs(method);
            transformed_items.push(quote! { #cleaned });
            continue;
        }

        if has_attr(&method.attrs, "getter") {
            let cleaned = strip_pyo3_method_attrs(method);
            transformed_items.push(quote! {
                #[pygetset]
                #cleaned
            });
            continue;
        }

        if has_attr(&method.attrs, "setter") {
            let cleaned = strip_pyo3_method_attrs(method);
            transformed_items.push(quote! {
                #[pygetset(setter)]
                #cleaned
            });
            continue;
        }

        if has_attr(&method.attrs, "staticmethod") {
            let cleaned = strip_pyo3_method_attrs(method);
            transformed_items.push(quote! {
                #[pystaticmethod]
                #cleaned
            });
            continue;
        }

        if has_attr(&method.attrs, "classmethod") {
            let cleaned = strip_pyo3_method_attrs(method);
            transformed_items.push(quote! {
                #[pyclassmethod]
                #cleaned
            });
            continue;
        }

        // Regular method (including magic methods like __repr__, __str__).
        // RustPython's #[pymethod] handles dunder names automatically.
        let cleaned = strip_pyo3_method_attrs(method);
        transformed_items.push(quote! {
            #[pymethod]
            #cleaned
        });
    }

    // Build the pyclass attribute for the impl block.
    let pyclass_attr = if has_new {
        quote! { #[::rustpython_vm::pyclass(with(::rustpython_vm::types::Constructor))] }
    } else {
        quote! { #[::rustpython_vm::pyclass] }
    };

    // Generate Constructor trait impl if needed.
    let constructor_impl = if let Some(ref new_fn) = new_method {
        Some(generate_constructor_impl(new_fn, self_ty)?)
    } else {
        None
    };

    Ok(quote! {
        #pyclass_attr
        impl #self_ty {
            #(#transformed_items)*
        }

        #constructor_impl
    })
}

/// Generate the `Constructor` trait implementation.
fn generate_constructor_impl(new_fn: &ImplItemFn, self_ty: &syn::Type) -> Result<TokenStream> {
    let params = collect_fn_params(new_fn)?;

    if params.is_empty() {
        // No-arg constructor
        Ok(quote! {
            impl ::rustpython_vm::types::Constructor for #self_ty {
                type Args = ::rustpython_vm::function::FuncArgs;

                fn py_new(
                    _cls: &::rustpython_vm::Py<::rustpython_vm::builtins::PyType>,
                    _args: Self::Args,
                    _vm: &::rustpython_vm::VirtualMachine,
                ) -> ::rustpython_vm::PyResult<Self> {
                    Ok(Self::new())
                }
            }
        })
    } else {
        let arg_types: Vec<&syn::Type> = params.iter().map(|(_, ty)| ty).collect();
        let arg_names: Vec<&syn::Ident> = params.iter().map(|(name, _)| name).collect();

        let bind_type = if params.len() == 1 {
            let ty = arg_types[0];
            quote! { (#ty,) }
        } else {
            quote! { (#(#arg_types),*) }
        };

        let destructure = if params.len() == 1 {
            let name = arg_names[0];
            quote! { let (#name,) = args; }
        } else {
            quote! { let (#(#arg_names),*) = args; }
        };

        Ok(quote! {
            impl ::rustpython_vm::types::Constructor for #self_ty {
                type Args = #bind_type;

                fn py_new(
                    _cls: &::rustpython_vm::Py<::rustpython_vm::builtins::PyType>,
                    args: Self::Args,
                    _vm: &::rustpython_vm::VirtualMachine,
                ) -> ::rustpython_vm::PyResult<Self> {
                    #destructure
                    Ok(Self::new(#(#arg_names),*))
                }
            }
        })
    }
}

/// Collect parameter names and types from a function (skipping `self`).
fn collect_fn_params(func: &ImplItemFn) -> Result<Vec<(syn::Ident, syn::Type)>> {
    let mut params = Vec::new();

    for arg in &func.sig.inputs {
        match arg {
            FnArg::Receiver(_) => continue,
            FnArg::Typed(pat_type) => {
                let name = match pat_type.pat.as_ref() {
                    Pat::Ident(pi) => pi.ident.clone(),
                    other => {
                        return Err(syn::Error::new_spanned(
                            other,
                            "unsupported argument pattern in #[new]",
                        ))
                    }
                };
                params.push((name, (*pat_type.ty).clone()));
            }
        }
    }

    Ok(params)
}

/// Check if a method has a specific pyo3 attribute (e.g., "new", "getter", etc.)
fn has_attr(attrs: &[syn::Attribute], name: &str) -> bool {
    attrs.iter().any(|attr| attr.path().is_ident(name))
}

/// Strip pyo3-specific attributes from a method, keeping other attributes.
fn strip_pyo3_method_attrs(method: &ImplItemFn) -> ImplItemFn {
    let pyo3_attrs = [
        "new",
        "getter",
        "setter",
        "staticmethod",
        "classmethod",
        "pyo3",
    ];
    let mut cleaned = method.clone();
    cleaned
        .attrs
        .retain(|attr| !pyo3_attrs.iter().any(|name| attr.path().is_ident(name)));
    cleaned
}
