use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{FnArg, ImplItem, ImplItemFn, ItemImpl, Pat, Result, ReturnType};

/// Expand `#[pymethods]` on an impl block.
///
/// Transforms a pyo3-style impl block into a rustpython-vm-style impl block:
/// - `#[new]` -> Constructor trait impl
/// - `__repr__`, `__str__`, etc. -> `#[pymethod]` (rustpython handles dunders)
/// - Regular methods -> `#[pymethod]`
/// - `#[getter]` / `#[setter]` -> `#[pygetset]` / `#[pygetset(setter)]`
/// - `#[staticmethod]` -> `#[pystaticmethod]`
/// - `#[classmethod]` -> `#[pyclassmethod]`
///
/// Also invokes the `__pyo3_accessors_StructName!()` macro (generated by
/// `#[pyclass]`) to include getter/setter methods for `#[pyo3(get, set)]` fields.
pub fn expand(_attr: TokenStream, input: ItemImpl) -> Result<TokenStream> {
    let self_ty = &input.self_ty;

    let mut has_new = false;
    let mut new_method: Option<ImplItemFn> = None;
    let mut transformed_items: Vec<TokenStream> = Vec::new();

    for item in &input.items {
        let ImplItem::Fn(method) = item else {
            // Pass through non-function items (type aliases, consts, etc.)
            transformed_items.push(quote! { #item });
            continue;
        };

        if has_attr(&method.attrs, "new") {
            has_new = true;
            new_method = Some(method.clone());
            // Keep the original method (without the #[new] attr) as a helper.
            let cleaned = strip_pyo3_method_attrs(method);
            transformed_items.push(quote! { #cleaned });
            continue;
        }

        if has_attr(&method.attrs, "getter") {
            let cleaned = strip_pyo3_method_attrs(method);
            transformed_items.push(quote! {
                #[pygetset]
                #cleaned
            });
            continue;
        }

        if has_attr(&method.attrs, "setter") {
            let cleaned = strip_pyo3_method_attrs(method);
            transformed_items.push(quote! {
                #[pygetset(setter)]
                #cleaned
            });
            continue;
        }

        if has_attr(&method.attrs, "staticmethod") {
            let cleaned = strip_pyo3_method_attrs(method);
            transformed_items.push(quote! {
                #[pystaticmethod]
                #cleaned
            });
            continue;
        }

        if has_attr(&method.attrs, "classmethod") {
            let cleaned = strip_pyo3_method_attrs(method);
            transformed_items.push(quote! {
                #[pyclassmethod]
                #cleaned
            });
            continue;
        }

        // Check if this is a slot method that RustPython forbids on #[pymethod].
        // These must be registered via trait impls or slot fixup instead.
        let fn_name_str = method.sig.ident.to_string();
        let is_slot_method = is_rustpython_slot_method(&fn_name_str);

        // Regular method (including magic methods like __repr__, __str__).
        // RustPython's #[pymethod] handles dunder names automatically.
        let cleaned = strip_pyo3_method_attrs(method);
        if is_slot_method {
            // Slot methods cannot use #[pymethod] in RustPython.
            // Emit as a plain method; slot wiring happens via fixup_dunder_slots.
            transformed_items.push(quote! { #cleaned });
        } else if returns_pyo3_result(&cleaned.sig.output) || has_pyo3_params(&cleaned) {
            // Method returns pyo3::PyResult<T> or has pyo3 shim types in params.
            // Generate a wrapper that converts between pyo3 and RustPython types.
            let wrapper = generate_pyresult_wrapper(&cleaned);
            transformed_items.push(wrapper);
        } else {
            transformed_items.push(quote! {
                #[pymethod]
                #cleaned
            });
        }
    }

    // Build the pyclass attribute for the impl block.
    let pyclass_attr = if has_new {
        quote! { #[::rustpython_vm::pyclass(with(::rustpython_vm::types::Constructor))] }
    } else {
        quote! { #[::rustpython_vm::pyclass] }
    };

    // Generate Constructor trait impl if needed.
    let constructor_impl = if let Some(ref new_fn) = new_method {
        Some(generate_constructor_impl(new_fn, self_ty)?)
    } else {
        None
    };

    Ok(quote! {
        #pyclass_attr
        impl #self_ty {
            #(#transformed_items)*
        }

        #constructor_impl
    })
}

/// Generate the `Constructor` trait implementation.
///
/// Uses `FuncArgs` for all constructors. For simple constructors (no args or
/// primitive args), tries to call the user's `init` method. For complex ones,
/// provides a best-effort implementation.
fn generate_constructor_impl(new_fn: &ImplItemFn, self_ty: &syn::Type) -> Result<TokenStream> {
    let params = collect_fn_params(new_fn)?;
    let fn_name = &new_fn.sig.ident;

    if params.is_empty() {
        // No-arg constructor
        Ok(quote! {
            impl ::rustpython_vm::types::Constructor for #self_ty {
                type Args = ::rustpython_vm::function::FuncArgs;

                fn py_new(
                    _cls: &::rustpython_vm::Py<::rustpython_vm::builtins::PyType>,
                    _args: Self::Args,
                    _vm: &::rustpython_vm::VirtualMachine,
                ) -> ::rustpython_vm::PyResult<Self> {
                    Ok(Self::#fn_name())
                }
            }
        })
    } else {
        // Check if all params are simple types (no lifetimes, no Bound, no Python)
        let has_complex_params = params.iter().any(|(_, ty)| {
            let s = quote!(#ty).to_string();
            s.contains("Bound") || s.contains("Python") || s.contains("'")
        });

        if has_complex_params {
            // Complex constructor: use FuncArgs and best-effort extraction
            Ok(quote! {
                impl ::rustpython_vm::types::Constructor for #self_ty {
                    type Args = ::rustpython_vm::function::FuncArgs;

                    fn py_new(
                        _cls: &::rustpython_vm::Py<::rustpython_vm::builtins::PyType>,
                        _args: Self::Args,
                        _vm: &::rustpython_vm::VirtualMachine,
                    ) -> ::rustpython_vm::PyResult<Self> {
                        let __py = ::pyo3::Python::from_vm(_vm);

                        // Construct a Bound<PyTuple> from positional args
                        let positional: Vec<::rustpython_vm::PyObjectRef> = _args.args;
                        let tuple_obj: ::rustpython_vm::PyObjectRef =
                            _vm.ctx.new_tuple(positional).into();
                        let _bound_args = ::pyo3::Bound::<::pyo3::types::PyTuple>::from_object(
                            __py, tuple_obj,
                        );

                        // Construct kwargs dict if present
                        let _bound_kwargs = if _args.kwargs.is_empty() {
                            None
                        } else {
                            let dict = _vm.ctx.new_dict();
                            for (k, v) in &_args.kwargs {
                                dict.set_item(&*_vm.ctx.new_str(k.as_str()), v.clone(), _vm)?;
                            }
                            let dict_obj: ::rustpython_vm::PyObjectRef = dict.into();
                            Some(::pyo3::Bound::<::pyo3::types::PyDict>::from_object(__py, dict_obj))
                        };

                        Err(_vm.new_type_error(
                            "Complex constructor not yet implemented via pyo3-rustpython shim."
                            .to_string(),
                        ))
                    }
                }
            })
        } else {
            // Simple constructor with primitive args
            let arg_types: Vec<&syn::Type> = params.iter().map(|(_, ty)| ty).collect();
            let arg_names: Vec<&syn::Ident> = params.iter().map(|(name, _)| name).collect();

            let bind_type = if params.len() == 1 {
                let ty = arg_types[0];
                quote! { (#ty,) }
            } else {
                quote! { (#(#arg_types),*) }
            };

            let destructure = if params.len() == 1 {
                let name = arg_names[0];
                quote! { let (#name,) = args; }
            } else {
                quote! { let (#(#arg_names),*) = args; }
            };

            Ok(quote! {
                impl ::rustpython_vm::types::Constructor for #self_ty {
                    type Args = #bind_type;

                    fn py_new(
                        _cls: &::rustpython_vm::Py<::rustpython_vm::builtins::PyType>,
                        args: Self::Args,
                        _vm: &::rustpython_vm::VirtualMachine,
                    ) -> ::rustpython_vm::PyResult<Self> {
                        #destructure
                        Ok(Self::#fn_name(#(#arg_names),*))
                    }
                }
            })
        }
    }
}

/// Collect parameter names and types from a function (skipping `self`).
fn collect_fn_params(func: &ImplItemFn) -> Result<Vec<(syn::Ident, syn::Type)>> {
    let mut params = Vec::new();

    for arg in &func.sig.inputs {
        match arg {
            FnArg::Receiver(_) => continue,
            FnArg::Typed(pat_type) => {
                let name = match pat_type.pat.as_ref() {
                    Pat::Ident(pi) => pi.ident.clone(),
                    other => {
                        return Err(syn::Error::new_spanned(
                            other,
                            "unsupported argument pattern in #[new]",
                        ))
                    }
                };
                params.push((name, (*pat_type.ty).clone()));
            }
        }
    }

    Ok(params)
}

/// Check if a dunder method name is one that RustPython reserves for slot
/// trait implementations (Hashable, Comparable, AsNumber, AsSequence, etc.).
/// These cannot be annotated with `#[pymethod]`.
fn is_rustpython_slot_method(name: &str) -> bool {
    matches!(
        name,
        "__hash__"
            | "__eq__"
            | "__ne__"
            | "__lt__"
            | "__le__"
            | "__gt__"
            | "__ge__"
            | "__richcmp__"
            | "__and__"
            | "__or__"
            | "__sub__"
            | "__xor__"
            | "__add__"
            | "__mul__"
            | "__truediv__"
            | "__floordiv__"
            | "__mod__"
            | "__pow__"
            | "__lshift__"
            | "__rshift__"
            | "__matmul__"
            | "__neg__"
            | "__pos__"
            | "__abs__"
            | "__invert__"
            | "__int__"
            | "__float__"
            | "__bool__"
            | "__iadd__"
            | "__isub__"
            | "__imul__"
            | "__iand__"
            | "__ior__"
            | "__ixor__"
            | "__contains__"
            | "__iter__"
            | "__next__"
            | "__len__"
            | "__getitem__"
            | "__setitem__"
            | "__delitem__"
            | "__reversed__"
            | "__reduce__"
    )
}

/// Check if a method has a specific pyo3 attribute (e.g., "new", "getter", etc.)
fn has_attr(attrs: &[syn::Attribute], name: &str) -> bool {
    attrs.iter().any(|attr| attr.path().is_ident(name))
}

/// Strip pyo3-specific attributes from a method, keeping other attributes.
fn strip_pyo3_method_attrs(method: &ImplItemFn) -> ImplItemFn {
    let pyo3_attrs = [
        "new",
        "getter",
        "setter",
        "staticmethod",
        "classmethod",
        "pyo3",
    ];
    let mut cleaned = method.clone();
    cleaned
        .attrs
        .retain(|attr| !pyo3_attrs.iter().any(|name| attr.path().is_ident(name)));
    cleaned
}

/// Check if a method has parameters that use pyo3 shim types.
/// These types are not directly compatible with RustPython's #[pymethod]
/// parameter extraction.
fn has_pyo3_params(method: &ImplItemFn) -> bool {
    for arg in &method.sig.inputs {
        if let FnArg::Typed(pt) = arg {
            let param_str = quote!(#pt).to_string();
            // Check for pyo3 types that need wrapping
            if param_str.contains("Python")
                || param_str.contains("Bound")
                || param_str.contains("Py <")
                || param_str.contains("Py<")
            {
                return true;
            }
        }
    }
    false
}

/// Check if a return type contains `PyResult`.
fn returns_pyo3_result(ret: &ReturnType) -> bool {
    match ret {
        ReturnType::Default => false,
        ReturnType::Type(_, ty) => {
            let s = quote!(#ty).to_string().replace(' ', "");
            s.contains("PyResult")
        }
    }
}

/// Extract the inner type T from `PyResult<T>`.
fn extract_pyresult_inner(ret: &ReturnType) -> Option<TokenStream> {
    match ret {
        ReturnType::Default => None,
        ReturnType::Type(_, ty) => {
            let s = quote!(#ty).to_string().replace(' ', "");
            if !s.contains("PyResult") {
                return None;
            }
            // Parse "PyResult<T>" or "pyo3::PyResult<T>" etc.
            // Find the angle brackets
            if let Some(start) = s.find('<') {
                if let Some(end) = s.rfind('>') {
                    let inner = &s[start + 1..end];
                    let inner_tokens: TokenStream = inner.parse().ok()?;
                    return Some(inner_tokens);
                }
            }
            None
        }
    }
}

/// Generate a wrapper for a method that uses pyo3 types.
///
/// The wrapper:
/// 1. Accepts RustPython-compatible parameters (filtering out `Python<'_>`)
/// 2. Constructs `Python<'_>` from the VM
/// 3. Calls the inner method with the original pyo3-style parameters
/// 4. Maps pyo3::PyErr to rustpython_vm::PyBaseExceptionRef (if PyResult)
fn generate_pyresult_wrapper(method: &ImplItemFn) -> TokenStream {
    let fn_name = &method.sig.ident;
    let inner_name = format_ident!("_pyo3_{}", fn_name);
    let vis = &method.vis;
    let attrs = &method.attrs;

    let is_result = returns_pyo3_result(&method.sig.output);

    // Separate params into categories:
    // - Python<'_> params: injected from vm, not in wrapper signature
    // - Bound<'_, T> / &Bound<'_, T> / Py<T> params: convert to/from PyObjectRef
    // - Other params: pass through as-is
    let mut wrapper_params: Vec<TokenStream> = Vec::new();
    let mut inner_call_args: Vec<TokenStream> = Vec::new();
    let mut conversion_stmts: Vec<TokenStream> = Vec::new();
    let mut all_params: Vec<&FnArg> = Vec::new();

    for arg in &method.sig.inputs {
        match arg {
            FnArg::Receiver(_) => continue,
            FnArg::Typed(pt) => {
                let ty_str = quote!(#pt.ty).to_string().replace(' ', "");
                let name = if let Pat::Ident(pi) = pt.pat.as_ref() {
                    pi.ident.clone()
                } else {
                    // Unsupported pattern; pass through
                    wrapper_params.push(quote! { #arg });
                    all_params.push(arg);
                    continue;
                };

                if ty_str.contains("Python") {
                    // Python<'_> param: inject from vm, not in wrapper
                    inner_call_args.push(quote! { __py });
                } else if ty_str.contains("Bound<") {
                    // Bound<'_, T> param: accept as PyObjectRef, convert
                    let wrapper_name = format_ident!("__raw_{}", name);
                    wrapper_params.push(quote! { #wrapper_name: ::rustpython_vm::PyObjectRef });
                    conversion_stmts.push(quote! {
                        let #name = ::pyo3::Bound::from_object(__py, #wrapper_name);
                    });
                    // If the original type was a reference, pass a reference
                    if ty_str.contains("&Bound") {
                        inner_call_args.push(quote! { &#name });
                    } else {
                        inner_call_args.push(quote! { #name });
                    }
                } else {
                    // Regular param: pass through as-is
                    wrapper_params.push(quote! { #arg });
                    inner_call_args.push(quote! { #name });
                }
                all_params.push(arg);
            }
        }
    }

    // Collect all params for the inner function (including Python<'_>)
    let inner_params: Vec<_> = method
        .sig
        .inputs
        .iter()
        .filter(|a| !matches!(a, FnArg::Receiver(_)))
        .collect();

    let inner_ret = &method.sig.output;
    let inner_body = &method.block;

    // Determine receiver type
    let receiver = method.sig.inputs.first().and_then(|a| {
        if let FnArg::Receiver(r) = a {
            Some(quote! { #r })
        } else {
            None
        }
    });
    let receiver = receiver.unwrap_or(quote! { &self });

    if is_result {
        let inner_type = extract_pyresult_inner(inner_ret).unwrap_or(quote! { () });
        quote! {
            #(#attrs)*
            #[pymethod]
            #vis fn #fn_name(#receiver, #(#wrapper_params,)* vm: &::rustpython_vm::VirtualMachine) -> ::rustpython_vm::PyResult<#inner_type> {
                let __py = ::pyo3::Python::from_vm(vm);
                #(#conversion_stmts)*
                self.#inner_name(#(#inner_call_args),*).map_err(|e| ::pyo3::err::into_vm_err(e))
            }

            #vis fn #inner_name(#receiver, #(#inner_params),*) #inner_ret #inner_body
        }
    } else {
        // Non-result method with pyo3 params: generate wrapper
        let ret_type = &method.sig.output;
        quote! {
            #(#attrs)*
            #[pymethod]
            #vis fn #fn_name(#receiver, #(#wrapper_params,)* vm: &::rustpython_vm::VirtualMachine) #ret_type {
                let __py = ::pyo3::Python::from_vm(vm);
                #(#conversion_stmts)*
                self.#inner_name(#(#inner_call_args),*)
            }

            #vis fn #inner_name(#receiver, #(#inner_params),*) #ret_type #inner_body
        }
    }
}
