pub mod bound_object;
pub mod conversion;
pub mod err;
pub mod exceptions;
pub mod instance;
pub mod pyclass;
pub mod python;
pub mod slots;
pub mod types;

pub use bound_object::BoundObject;
pub use conversion::{FromPyObject, IntoPy, IntoPyObject, ToPyObject};
pub use err::{PyErr, PyResult};
pub use instance::{Bound, Borrowed, Py, PyRef, PyRefMut};
pub use pyclass::CompareOp;
pub use python::Python;
pub use pyo3_rustpython_derive::{pyclass, pyfunction, pymethods, pymodule};

/// Trait for types that have Python type information.
pub trait PyTypeInfo {
    const NAME: &'static str;
    const MODULE: Option<&'static str>;
}

/// Extension trait providing `type_object(py)` for pyclass types.
pub trait PyTypeObjectExt: rustpython_vm::class::StaticType {
    fn type_object(py: Python<'_>) -> Bound<'_, types::PyType> {
        let type_ref = Self::static_type();
        let obj: rustpython_vm::PyObjectRef = type_ref.to_owned().into();
        Bound::from_object(py, obj)
    }
}

/// Blanket implementation for all types that have StaticType.
impl<T: rustpython_vm::class::StaticType> PyTypeObjectExt for T {}

/// Trait for registering property accessors generated by `#[pyclass]`
/// for fields annotated with `#[pyo3(get)]` / `#[pyo3(set)]`.
///
/// This trait bridges the gap between `#[pyclass]` (which knows about fields)
/// and `#[pymethods]` (which generates the `PyClassImpl` block). Since
/// RustPython only allows a single `#[pyclass]` impl block per type,
/// accessor methods are registered separately via this trait.
pub trait Pyo3Accessors {
    fn __pyo3_register_accessors(
        ctx: &rustpython_vm::Context,
        class: &'static rustpython_vm::Py<rustpython_vm::builtins::PyType>,
    );
}

/// Wrapper that makes a raw `PyModuleDef` pointer safe to store in a `static`.
///
/// `PyModuleDef` is not `Sync` because it embeds `&'static PyStrInterned` whose
/// refcount uses `Cell`. In practice every user of this crate is single-threaded
/// (WASM or a single-VM host), so the `unsafe impl` is sound.
#[doc(hidden)]
pub struct SyncModuleDefPtr(pub *const rustpython_vm::builtins::PyModuleDef);
unsafe impl Sync for SyncModuleDefPtr {}
unsafe impl Send for SyncModuleDefPtr {}

// Re-export paste so `wrap_pyfunction!` works without callers needing it directly.
#[doc(hidden)]
pub use paste;

/// Marker trait for PyTuple methods. This is a compatibility shim for
/// `pyo3::types::PyTupleMethods`.
pub trait PyTupleMethods {}
impl<'py> PyTupleMethods for Bound<'py, types::PyTuple> {}

pub mod prelude {
    pub use crate::bound_object::BoundObject;
    pub use crate::conversion::{FromPyObject, IntoPy, IntoPyObject, ToPyObject};
    pub use crate::err::{PyErr, PyResult};
    pub use crate::instance::{Bound, Borrowed, Py, PyRef, PyRefMut};
    pub use crate::pyclass::CompareOp;
    pub use crate::python::Python;
    pub use crate::types::{
        PyAny, PyBool, PyBytes, PyDict, PyFloat, PyInt, PyIterator, PyList, PyLong, PyMapping,
        PyModule, PyNone, PySet, PyString, PyTuple, PyType,
    };
    pub use crate::Pyo3Accessors;
    pub use crate::PyTypeInfo;
    pub use crate::PyTypeObjectExt;
    pub use pyo3_rustpython_derive::{pyclass, pyfunction, pymethods, pymodule};

    pub use crate::wrap_pyfunction;
}

/// Creates a Python callable from a `#[pyfunction]`-annotated function.
///
/// Usage: `wrap_pyfunction!(fn_name, module_or_py)`
///
/// Expands to `Ok::<_, PyErr>(__pyo3_fn_<name>(module.py()))`.
#[macro_export]
macro_rules! wrap_pyfunction {
    ($func:ident, $module:expr) => {
        ::pyo3::paste::paste! {
            Ok::<_, $crate::PyErr>([<__pyo3_fn_ $func>]($module.py()))
        }
    };
}
